-- Datos de ejemplo realistas para SolarWeb
-- Ejecutar en Supabase SQL Editor para poblar la base de datos

INSERT INTO contact_messages (nombre, empresa, email, telefono, servicio, factura, mensaje, status, crmNote, created_at) VALUES
('Carlos Rodríguez Mendoza', 'Manufacturas del Norte S.A. de C.V.', 'carlos.rodriguez@manufacturasnorte.com', '55-1234-5678', 'Instalación Comercial', 'Sí', 'Necesitamos cotización para techo industrial de 2,000m² en Monterrey. Consumo actual de 15,000 kWh/mes.', 'Cerrado', 'Cliente VIP. Proyecto aprobado por junta directiva. Instalación programada para Q2.', '2026-03-15 09:30:00'),
('María García López', NULL, 'maria.garcia.85@gmail.com', '33-3456-7890', 'Instalación Residencial', 'No', 'Vivo en Guadalajara, casa de 180m². Quiero saber cuántos paneles necesito y el costo total.', 'En Proceso', 'Interesada en sistema de 5kW. Envió recibos de CFE para análisis. Esperando propuesta final.', '2026-03-16 14:22:00'),
('Roberto Hernández Silva', 'Logística Veloz Mexicana', 'roberto.hernandez@logisticaveloz.com.mx', '81-2345-6789', 'Instalación Comercial', 'Sí', 'Flotilla de 50 camiones de reparto. Queremos instalar paneles en nuestra bodega en Nuevo León.', 'Nuevo', 'Potencial cliente grande. Requiere visita técnica y análisis de consumo de flota eléctrica.', '2026-03-17 11:45:00'),
('Ana Patricia Morales', NULL, 'paty.morales@outlook.com', '55-9876-5432', 'Instalación Residencial', 'Sí', 'Casa en CDMX, 2 plantas, 4 habitaciones. Aire acondicionado en todas. Recibo de CFE de $2,800 mensuales.', 'En Proceso', 'Cliente con alto consumo. Sistema de 7kW recomendado. En negociación de financiamiento.', '2026-03-18 16:10:00'),
('Luis Fernando Torres', 'Torres Distribuidores S.A.', 'luis.torres@torresdistribuidores.com', '66-1234-5678', 'Instalación Comercial', 'Sí', 'Tenemos 3 sucursales en Hermosillo. Queremos empezar con la principal y luego expandir.', 'Cerrado', 'Contrato firmado por $450,000. Primera instalación completada exitosamente.', '2026-03-10 08:00:00'),
('Carmen Beatriz Ruiz', NULL, 'carmen.ruiz.familia@gmail.com', '99-3456-7890', 'Instalación Residencial', 'No', 'Vivo en Mérida, casa nueva de 200m². Quiero sistema desde cero.', 'Nuevo', 'Cliente pre-aprobado para crédito hipotecario verde. Esperando cotización final.', '2026-03-19 13:30:00'),
('Jorge Alberto Vargas', 'Vargas Alimentos S.A. de C.V.', 'jorge.vargas@vargasalimentos.com', '22-3456-7890', 'Instalación Comercial', 'Sí', 'Planta procesadora en Puebla. Consumo industrial de 25,000 kWh/mes. Necesitamos urgente.', 'En Proceso', 'Cliente corporativo grande. Propuesta de $850,000 en revisión legal. Requiere permisos municipales.', '2026-03-12 10:15:00'),
('Diana Carolina Santos', NULL, 'diana.santos.profesional@gmail.com', '55-4567-8901', 'Instalación Residencial', 'Sí', 'Departamento en Polanco, 120m². Edificio con políticas de energía renovable.', 'Cerrado', 'Venta completada. Sistema de 3kW instalado. Cliente muy satisfecha, nos refirió 2 vecinos.', '2026-03-05 15:45:00'),
('Miguel Ángel Castro', 'Castro Construcciones', 'miguel.castro@castroconstrucciones.com.mx', '44-2345-6789', 'Instalación Comercial', 'Sí', 'Desarrolladora inmobiliaria. Queremos paneles en 3 proyectos nuevos en Guanajuato.', 'Nuevo', 'Potencial cliente recurrente. 3 proyectos de 50 casas cada uno. Visita programada para próxima semana.', '2026-03-20 09:00:00'),
('Patricia Guadalupe Mendoza', NULL, 'patty.mendoza.terra@gmail.com', '77-1234-5678', 'Instalación Residencial', 'No', 'Vivo en Torreón. Casa con piscina y alberca. Recibos muy altos en verano.', 'En Proceso', 'Análisis de consumo completado. Sistema de 8kW recomendado por alto consumo de aire acondicionado.', '2026-03-21 12:20:00'),
('Francisco Javier Pérez', 'Pérez Importaciones S.A.', 'fco.perez@perezimportaciones.com', '65-3456-7890', 'Instalación Comercial', 'Sí', 'Bodega en Tijuana. Operaciones 24/7. Queremos maximizar ahorro energético.', 'Cerrado', 'Proyecto de $650,000 completado. Cliente considera segunda fase para 2027.', '2026-03-08 14:30:00'),
('Rosa Elena Flores', NULL, 'rosa.flores.hogar@gmail.com', '55-6789-0123', 'Instalación Residencial', 'Sí', 'Casa en Querétaro, 150m². Quiero independencia energética total.', 'Nuevo', 'Interesada en sistema con baterías. Presupuesto alto, buscando solución premium.', '2026-03-22 17:40:00'),
('José Luis Ramírez', 'Ramírez Automotriz', 'jose.ramirez@ramirezautomotriz.com', '33-1234-5678', 'Instalación Comercial', 'Sí', 'Agencia de autos en Guadalajara. 10,000m² de techo disponible.', 'En Proceso', 'Propuesta de $1.2M en revisión. Cliente considera leasing de equipos.', '2026-03-13 11:00:00'),
('Leticia Mariana Ortiz', NULL, 'leticia.ortiz.profesional@gmail.com', '81-4567-8901', 'Instalación Residencial', 'No', 'Médica, trabajo desde casa. Necesito energía confiable para consultorio virtual.', 'Cerrado', 'Sistema de 4kW con backup. Cliente muy contenta, nos refirió a su hospital.', '2026-03-07 10:45:00'),
('Antonio de Jesús Gómez', 'Gómez Retail S.A. de C.V.', 'antonio.gomez@gomezretail.com', '55-2345-6789', 'Instalación Comercial', 'Sí', 'Cadena de tiendas en CDMX. 15 sucursales. Queremos empezar con programa piloto.', 'Nuevo', 'Cliente estratégico. Programa piloto de 3 tiendas. Potencial expansión a todas las sucursales.', '2026-03-23 08:30:00'),
('Gabriela Alejandra Jiménez', NULL, 'gaby.jimenez.arte@gmail.com', '99-6789-0123', 'Instalación Residencial', 'Sí', 'Artista plástica. Taller en casa. Necesito energía para equipos de arte digital.', 'En Proceso', 'Cliente creativa con necesidades especiales. Sistema de 6kW con estabilización.', '2026-03-24 15:15:00'),
('Raúl Eduardo Morales', 'Morales Transportes', 'raul.morales@moralestransportes.com.mx', '66-4567-8901', 'Instalación Comercial', 'Sí', 'Terminal de autobuses en Mexicali. Operaciones intensivas en verano.', 'Cerrado', 'Proyecto de $980,000. Cliente considera expansión a otras terminales.', '2026-03-09 13:20:00'),
('Verónica Leticia Sánchez', NULL, 'vero.sanchez.verde@gmail.com', '22-6789-0123', 'Instalación Residencial', 'No', 'Casa ecológica en Puebla. Quiero sistema 100% renovable.', 'Nuevo', 'Cliente con visión ambiental. Interesada en sistema híbrido con baterías de litio.', '2026-03-25 09:45:00'),
('Daniel Alejandro Reyes', 'Reyes Tecnología S.A.', 'daniel.reyes@reyestecnologia.com', '44-6789-0123', 'Instalación Comercial', 'Sí', 'Centro de datos en León. Requerimientos críticos de energía.', 'En Proceso', 'Cliente corporativo con necesidades especiales. Sistema de redundancia requerido.', '2026-03-14 16:30:00'),
('María del Carmen Castro', NULL, 'maricarmen.castro.hogar@gmail.com', '77-4567-8901', 'Instalación Residencial', 'Sí', 'Pensando en futuro. Quiero vender excedentes a CFE.', 'Cerrado', 'Sistema de 5kW con medidor bidireccional. Primera cliente con venta de excedentes.', '2026-03-11 11:30:00'),
('Hugo Ricardo Navarro', 'Navarro Construcciones', 'hugo.navarro@navarroconstrucciones.com', '65-6789-0123', 'Instalación Comercial', 'Sí', 'Desarrollador de fraccionamientos. Queremos incluir paneles en todas las casas.', 'Nuevo', 'Socio estratégico potencial. Acuerdo para 200 casas en nuevo desarrollo.', '2026-03-26 10:00:00');
