-- ==============================================================================
-- SCRIPT DE INICIALIZACIÓN PARA SUPABASE - PANEL DE ADMINISTRACIÓN SOLAR WEB
-- ==============================================================================
-- Instrucciones:
-- 1. Copia todo este código.
-- 2. Ve al panel de control de Supabase (https://supabase.com/dashboard).
-- 3. Entra a tu proyecto (ojswxnqgqikzmzihtmfu).
-- 4. Ve a la sección "SQL Editor" en el menú lateral izquierdo.
-- 5. Haz clic en "New Query", pega este código y presiona "Run" (Ejecutar).
-- ==============================================================================

-- 1. Crear la tabla principal de mensajes/cotizaciones (CRM)
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    empresa TEXT,
    email TEXT NOT NULL,
    telefono TEXT NOT NULL,
    servicio TEXT,
    factura TEXT,
    mensaje TEXT,
    status TEXT DEFAULT 'Nuevo'::text,
    "crmNote" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar la Seguridad a Nivel de Fila (RLS) en la tabla
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- 3. Crear políticas de acceso (Políticas RLS)

-- Permitir a CUALQUIER usuario (incluso no autenticados) insertar nuevos mensajes.
-- Esto es necesario para que el formulario público de la web funcione.
CREATE POLICY "Permitir insertar a usuarios anonimos"
    ON public.contact_messages
    FOR INSERT
    TO public
    WITH CHECK (true);

-- Permitir a usuarios AUTENTICADOS (el administrador) leer, actualizar y eliminar mensajes.
CREATE POLICY "Permitir leer a usuarios autenticados"
    ON public.contact_messages
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Permitir actualizar a usuarios autenticados"
    ON public.contact_messages
    FOR UPDATE
    TO authenticated
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Permitir eliminar a usuarios autenticados"
    ON public.contact_messages
    FOR DELETE
    TO authenticated
    USING (true);

-- ==============================================================================
-- CREACIÓN DEL USUARIO ADMINISTRADOR DE PRUEBA
-- Nota: Para seguridad, es mejor crear el usuario manualmente en:
-- Supabase Dashboard -> Authentication -> Users -> "Add user"
-- ==============================================================================
-- Correo sugerido: admin@ejemplo.com
-- Contraseña sugerida: admin123456
