-- ==============================================================================
-- ESQUEMA COMPLETO DE BASE DE DATOS PARA PANEL DE ADMINISTRACIÓN SOLAR WEB
-- ==============================================================================
-- Instrucciones:
-- 1. Copia todo este código.
-- 2. Ve al panel de control de Supabase (https://supabase.com/dashboard).
-- 3. Entra a tu proyecto (ojswxnqgqikzmzihtmfu).
-- 4. Ve a la sección "SQL Editor" en el menú lateral izquierdo.
-- 5. Haz clic en "New Query", pega este código y presiona "Run" (Ejecutar).
-- ==============================================================================

-- 1. TABLA PRINCIPAL DE MENSAJES/COTIZACIONES (CRM)
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    empresa TEXT,
    email TEXT NOT NULL,
    telefono TEXT NOT NULL,
    servicio TEXT,
    factura TEXT,
    mensaje TEXT,
    status TEXT DEFAULT 'Nuevo'::text,
    "crmNote" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABLA DE SERVICIOS (CATÁLOGO)
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    base_price DECIMAL(10,2),
    category TEXT DEFAULT 'residencial'::text, -- 'residencial', 'comercial', 'industrial'
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABLA DE PROYECTOS (SEGUIMIENTO DE INSTALACIONES)
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT REFERENCES public.contact_messages(id) ON DELETE CASCADE,
    project_name TEXT NOT NULL,
    service_type TEXT NOT NULL,
    status TEXT DEFAULT 'Planificación'::text, -- 'Planificación', 'En Progreso', 'Completado', 'Cancelado'
    estimated_cost DECIMAL(12,2),
    actual_cost DECIMAL(12,2),
    start_date DATE,
    completion_date DATE,
    address TEXT,
    city TEXT,
    state TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABLA DE CITAS/REUNIONES
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT REFERENCES public.contact_messages(id) ON DELETE CASCADE,
    project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT,
    appointment_date TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_minutes INTEGER DEFAULT 60,
    status TEXT DEFAULT 'Programada'::text, -- 'Programada', 'Completada', 'Cancelada', 'Reprogramada'
    location TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. TABLA DE DOCUMENTOS (CONTRATOS, FACTURAS, ETC)
CREATE TABLE IF NOT EXISTS public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT REFERENCES public.contact_messages(id) ON DELETE CASCADE,
    project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
    document_type TEXT NOT NULL, -- 'Contrato', 'Factura', 'Cotización', 'Manual', 'Certificado'
    title TEXT NOT NULL,
    file_url TEXT,
    file_name TEXT,
    file_size BIGINT,
    mime_type TEXT,
    description TEXT,
    is_public BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. TABLA DE KITS SOLARES (CATÁLOGO DE PRODUCTOS)
CREATE TABLE IF NOT EXISTS public.kits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL, -- 'Residencial', 'Comercial', 'Industrial'
    capacity INTEGER NOT NULL, -- Capacidad en watts
    price DECIMAL(10,2) NOT NULL, -- Precio en MXN
    stock INTEGER DEFAULT 0,
    description TEXT,
    panels INTEGER NOT NULL, -- Número de paneles
    inverter DECIMAL(6,2) NOT NULL, -- Capacidad del inversor en kW
    battery DECIMAL(6,2), -- Capacidad de batería en kWh (opcional)
    warranty INTEGER, -- Garantía en años (opcional)
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. TABLA DE SEGUIMIENTO DE COMUNICACIONES
CREATE TABLE IF NOT EXISTS public.communications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT REFERENCES public.contact_messages(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- 'Email', 'Llamada', 'WhatsApp', 'Visita', 'Nota'
    subject TEXT,
    content TEXT NOT NULL,
    direction TEXT DEFAULT 'Saliente'::text, -- 'Entrante', 'Saliente'
    status TEXT DEFAULT 'Enviado'::text, -- 'Enviado', 'Recibido', 'Pendiente', 'Fallido'
    next_follow_up DATE,
    created_by TEXT, -- ID del usuario que creó la comunicación
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. HABILITAR SEGURIDAD A NIVEL DE FILA (RLS) EN TODAS LAS TABLAS
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.communications ENABLE ROW LEVEL SECURITY;

-- 8. POLÍTICAS DE ACCESO (RLS)

-- Eliminar políticas existentes antes de crear nuevas (para evitar errores)
DROP POLICY IF EXISTS "Permitir insertar a usuarios anonimos" ON public.contact_messages;
DROP POLICY IF EXISTS "Permitir todo a usuarios autenticados" ON public.contact_messages;
DROP POLICY IF EXISTS "Permitir leer servicios a usuarios autenticados" ON public.services;
DROP POLICY IF EXISTS "Permitir gestionar servicios a usuarios autenticados" ON public.services;
DROP POLICY IF EXISTS "Permitir todo a usuarios autenticados" ON public.projects;
DROP POLICY IF EXISTS "Permitir todo a usuarios autenticados" ON public.appointments;
DROP POLICY IF EXISTS "Permitir todo a usuarios autenticados" ON public.documents;
DROP POLICY IF EXISTS "Permitir todo a usuarios autenticados" ON public.kits;
DROP POLICY IF EXISTS "Permitir todo a usuarios autenticados" ON public.communications;

-- Tabla contact_messages
CREATE POLICY "Permitir insertar a usuarios anonimos" ON public.contact_messages
    FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Permitir todo a usuarios autenticados" ON public.contact_messages
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Tabla services (solo lectura pública para usuarios autenticados)
CREATE POLICY "Permitir leer servicios a usuarios autenticados" ON public.services
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Permitir gestionar servicios a usuarios autenticados" ON public.services
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Tabla projects
CREATE POLICY "Permitir todo a usuarios autenticados" ON public.projects
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Tabla appointments
CREATE POLICY "Permitir todo a usuarios autenticados" ON public.appointments
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Tabla documents
CREATE POLICY "Permitir todo a usuarios autenticados" ON public.documents
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Tabla kits
CREATE POLICY "Permitir todo a usuarios autenticados" ON public.kits
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Tabla communications
CREATE POLICY "Permitir todo a usuarios autenticados" ON public.communications
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 9. ÍNDICES PARA MEJORAR RENDIMIENTO
CREATE INDEX IF NOT EXISTS idx_contact_messages_status ON public.contact_messages(status);
CREATE INDEX IF NOT EXISTS idx_contact_messages_created_at ON public.contact_messages(created_at);
CREATE INDEX IF NOT EXISTS idx_contact_messages_email ON public.contact_messages(email);
CREATE INDEX IF NOT EXISTS idx_projects_status ON public.projects(status);
CREATE INDEX IF NOT EXISTS idx_projects_contact_id ON public.projects(contact_id);
CREATE INDEX IF NOT EXISTS idx_appointments_date ON public.appointments(appointment_date);
CREATE INDEX IF NOT EXISTS idx_appointments_status ON public.appointments(status);
CREATE INDEX IF NOT EXISTS idx_communications_contact_id ON public.communications(contact_id);
CREATE INDEX IF NOT EXISTS idx_communications_created_at ON public.communications(created_at);
CREATE INDEX IF NOT EXISTS idx_kits_category ON public.kits(category);
CREATE INDEX IF NOT EXISTS idx_kits_is_active ON public.kits(is_active);
CREATE INDEX IF NOT EXISTS idx_kits_created_at ON public.kits(created_at);

-- 10. TRIGGERS PARA ACTUALIZAR updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER handle_contact_messages_updated_at
    BEFORE UPDATE ON public.contact_messages
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER handle_projects_updated_at
    BEFORE UPDATE ON public.projects
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER handle_appointments_updated_at
    BEFORE UPDATE ON public.appointments
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER handle_kits_updated_at
    BEFORE UPDATE ON public.kits
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- 11. DATOS INICIALES (SERVICIOS)
INSERT INTO public.services (name, description, base_price, category) VALUES
('Instalación Residencial', 'Instalación completa de sistema solar para vivienda residencial', 85000.00, 'residencial'),
('Instalación Comercial', 'Sistema solar para negocios y comercios', 350000.00, 'comercial'),
('Instalación Industrial', 'Proyectos industriales a gran escala', 750000.00, 'industrial'),
('Mantenimiento Preventivo', 'Mantenimiento semestral del sistema solar', 2500.00, 'servicio'),
('Mantenimiento Correctivo', 'Reparación de componentes del sistema', 5000.00, 'servicio'),
('Consultoría Solar', 'Asesoría especializada en energía solar', 10000.00, 'consultoría'),
('Auditoría Energética', 'Análisis completo del consumo energético', 8000.00, 'consultoría')
ON CONFLICT (name) DO NOTHING;

-- 12. DATOS INICIALES (KITS SOLARES)
INSERT INTO public.kits (name, category, capacity, price, stock, description, panels, inverter, battery, warranty, is_active) VALUES
('Kit Residencial Básico 1kW', 'Residencial', 1000, 25000.00, 15, 'Kit ideal para viviendas pequeñas con consumo básico', 4, 1.5, 2.5, 25, true),
('Kit Residencial Estándar 3kW', 'Residencial', 3000, 55000.00, 12, 'Perfecto para familias con consumo medio', 8, 3.5, 5.0, 25, true),
('Kit Residencial Premium 5kW', 'Residencial', 5000, 85000.00, 8, 'Sistema completo para viviendas grandes', 12, 6.0, 10.0, 25, true),
('Kit Comercial 10kW', 'Comercial', 10000, 180000.00, 5, 'Para pequeñas y medianas empresas', 20, 12.0, 20.0, 20, true),
('Kit Comercial 25kW', 'Comercial', 25000, 350000.00, 3, 'Sistema robusto para empresas medianas', 40, 30.0, 50.0, 20, true),
('Kit Industrial 50kW', 'Industrial', 50000, 650000.00, 2, 'Para grandes instalaciones industriales', 80, 60.0, 100.0, 15, true),
('Kit Industrial 100kW', 'Industrial', 100000, 1200000.00, 1, 'Sistema de alta capacidad para industria pesada', 160, 120.0, 200.0, 15, true)
ON CONFLICT DO NOTHING;

-- 13. VISTAS ÚTILES PARA EL PANEL

-- Vista de clientes con información completa
CREATE OR REPLACE VIEW public.client_dashboard AS
SELECT 
    cm.id,
    cm.nombre,
    cm.empresa,
    cm.email,
    cm.telefono,
    cm.servicio,
    cm.status,
    cm."crmNote",
    cm.created_at,
    COUNT(p.id) as project_count,
    COUNT(a.id) as appointment_count,
    MAX(a.appointment_date) as last_appointment
FROM public.contact_messages cm
LEFT JOIN public.projects p ON cm.id = p.contact_id
LEFT JOIN public.appointments a ON cm.id = a.contact_id
GROUP BY cm.id, cm.nombre, cm.empresa, cm.email, cm.telefono, cm.servicio, cm.status, cm."crmNote", cm.created_at;

-- Vista de proyectos con detalles del cliente
CREATE OR REPLACE VIEW public.project_dashboard AS
SELECT 
    p.id,
    p.project_name,
    p.service_type,
    p.status,
    p.estimated_cost,
    p.actual_cost,
    p.start_date,
    p.completion_date,
    p.city,
    p.state,
    cm.nombre as client_name,
    cm.empresa as client_empresa,
    cm.email as client_email,
    cm.telefono as client_phone
FROM public.projects p
JOIN public.contact_messages cm ON p.contact_id = cm.id;

-- 14. FUNCIONES ÚTILES

-- Función para obtener estadísticas del dashboard
CREATE OR REPLACE FUNCTION public.get_dashboard_stats()
RETURNS JSON AS $$
DECLARE
    result JSON;
BEGIN
    SELECT json_build_object(
        'total_leads', (SELECT COUNT(*) FROM public.contact_messages),
        'new_leads', (SELECT COUNT(*) FROM public.contact_messages WHERE status = 'Nuevo'),
        'in_process', (SELECT COUNT(*) FROM public.contact_messages WHERE status = 'En Proceso'),
        'closed_sales', (SELECT COUNT(*) FROM public.contact_messages WHERE status = 'Cerrado'),
        'total_projects', (SELECT COUNT(*) FROM public.projects),
        'active_projects', (SELECT COUNT(*) FROM public.projects WHERE status IN ('Planificación', 'En Progreso')),
        'pending_appointments', (SELECT COUNT(*) FROM public.appointments WHERE status = 'Programada' AND appointment_date > NOW()),
        'this_month_leads', (SELECT COUNT(*) FROM public.contact_messages WHERE created_at >= date_trunc('month', CURRENT_DATE)),
        'total_kits', (SELECT COUNT(*) FROM public.kits),
        'active_kits', (SELECT COUNT(*) FROM public.kits WHERE is_active = true),
        'total_stock_value', (SELECT COALESCE(SUM(price * stock), 0) FROM public.kits WHERE is_active = true)
    ) INTO result;
    
    RETURN result;
END;
$$ LANGUAGE plpgsql;

-- ==============================================================================
-- INSTRUCCIONES FINALES
-- ==============================================================================
-- 1. Crear usuario administrador manualmente en:
--    Supabase Dashboard -> Authentication -> Users -> "Add user"
--    Correo: admin@ejemplo.com
--    Contraseña: admin123456

-- 2. Configurar Storage para documentos (opcional):
--    Supabase Dashboard -> Storage -> New bucket
--    Nombre: documents
--    Políticas públicas según necesidad

-- 3. El panel ahora tiene soporte completo para:
--    - Gestión de clientes y leads
--    - Seguimiento de proyectos
--    - Agenda de citas
--    - Gestión de documentos
--    - Gestión de kits solares (catálogo de productos)
--    - Historial de comunicaciones
--    - Estadísticas y reportes
-- ==============================================================================
